config/routes.rb
EpetitionUnzensiert::Application.routes.draw do
  devise_for :users

  get '/browser/:petition_id' => 'browser#show', :as => :browser_show, :petition_id => /\d+/
  get '/browser/index' => 'browser#index'

  resources :meinungen, :only => [] do
    collection do
      patch '/bin_unterstuetzer/:petition_id' => 'meinungen#bin_unterstuetzer', :as => :bin_unterstuetzer, :petition_id => /\d+/
      patch '/bin_dagegen/:petition_id' => 'meinungen#bin_dagegen', :as => :bin_dagegen, :petition_id => /\d+/
      patch '/habe_keine_meinung/:petition_id' => 'meinungen#habe_keine_meinung', :as => :habe_keine_meinung, :petition_id => /\d+/
      patch '/ist_spam/:petition_id' => 'meinungen#ist_spam', :as => :ist_spam, :petition_id => /\d+/
      patch '/ist_kein_spam/:petition_id' => 'meinungen#ist_kein_spam', :as => :ist_kein_spam, :petition_id => /\d+/
    end
  end

  resources :static_sites
  resources :users, :only => [:index, :show] do 
    resources :petitionen do
      patch '/jetzt_veroeffentlichen' => 'petitionen#jetzt_veroeffentlichen'
      patch '/entzensieren' => 'petitionen#entzensieren'
      patch '/admin_zensieren' => 'petitionen#admin_zensieren'
      patch '/nicht_admin_zensieren' => 'petitionen#nicht_admin_zensieren'
    end
    resources :meinungen, :only => [:index]
    patch '/ist_spammer' => 'users#ist_spammer'
    patch '/ist_kein_spammer' => 'users#ist_kein_spammer'
  end

  get '/:static_site_path' => 'static_sites#show_static_site'
  root 'static_sites#show_static_site' # index.html aus CMS ist Startseite

  get '*path' => 'application#notfound404'
end

app/controllers/petitionen_controller.rb
# encoding: utf-8
#
# https://www.epetition-unzensiert.de - Web-Application to publish censored petitions.
# Copyright (C) 2013 Jan Kechel
#  
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
class PetitionenController < ApplicationController
  include ActionView::Helpers::SanitizeHelper

  before_action :authenticate_user!

  before_filter :except => [] do
    if current_user.is_admin && params[:user_id]
      @foruser = User.find(params[:user_id])
    else
      if params[:user_id] && params[:user_id].to_i != current_user.id
        raise ForbiddenException.new
      end
      @foruser = current_user
    end
  end

  before_action :set_petition, only: [:show, :edit, :update, :destroy]
  before_action :set_petition_id, only: [:jetzt_veroeffentlichen, :entzensieren, :admin_zensieren, :nicht_admin_zensieren]

  before_filter :only => [:edit, :update, :destroy] do
    if @petition.datum_veroeffentlicht
      if !current_user || !current_user.is_admin
        redirect_to browser_show_path(@petition)
        return
      end
    end
  end

  before_filter :only => [:create, :update] do
    params[:petition][:inhalt] = sanitize(params[:petition][:inhalt], :tags=>[])
    params[:petition][:titel] = sanitize(params[:petition][:titel], :tags=>[])
  end

  # GET /petitionen
  def index
    @petitionen = @foruser.petitionen.page(params[:page])
  end

  # GET /petitionen/1
  def show
  end

  # GET /petitionen/new
  def new
    @petition = @foruser.petitionen.new
  end

  # GET /petitionen/1/edit
  def edit
  end

  # POST /petitionen
  def create
    @petition = @foruser.petitionen.new(params.require(:petition).permit(:titel, :inhalt))
    @petition.datum_erstellt = DateTime.now
    @petition.datum_zuletzt_bearbeitet = DateTime.now

    if @petition.save
      redirect_to [@foruser, @petition], notice: 'Petition wurde erstellt.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /petitionen/1
  def update
    if @petition.update(params.require(:petition).permit(:titel, :inhalt))
      @petition.datum_zuletzt_bearbeitet = DateTime.now
      @petition.save
      redirect_to [@foruser, @petition], notice: 'Petition wurde gespeichert.'
    else
      render action: 'edit'
    end
  end

  def jetzt_veroeffentlichen
    if !@petition.datum_veroeffentlicht
      @petition.datum_veroeffentlicht = DateTime.now
      @petition.save!
    end

    redirect_to browser_show_path(@petition), notice: 'Petition wurde veröffentlicht und wird jetzt allen Besuchern angezeigt.'
  end

  def entzensieren
    @petition.datum_entzensiert = DateTime.now
    @petition.save
    redirect_to [@foruser, @petition]
  end
  def admin_zensieren
    @petition.ist_zensiert_von_admin = true
    @petition.save
    redirect_to [@foruser, @petition]
  end
  def nicht_admin_zensieren
    @petition.ist_zensiert_von_admin = false
    @petition.save
    redirect_to [@foruser, @petition]
  end

  # DELETE /petitionen/1
  def destroy
    @petition.destroy
    redirect_to petitionen_url, notice: 'Petition wurde gelöscht.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_petition
      @petition = @foruser.petitionen.find(params[:id])
    end
    def set_petition_id
      @petition = @foruser.petitionen.find(params[:petition_id])
    end
end

app/helpers/petitionen_helper.rb
# encoding: utf-8
#
# https://www.epetition-unzensiert.de - Web-Application to publish censored petitions.
# Copyright (C) 2013 Jan Kechel
#  
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
module PetitionenHelper
end

app/views/petitionen/_as_li.html.erb
<%
#
# https://www.epetition-unzensiert.de - Web-Application to publish censored petitions.
# Copyright (C) 2013 Jan Kechel
#  
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
%>

<li>
  <a href="<%= user_petition_path(foruser, petition) %>">
    <span style="display:inline-block;width:120px;"><%= petition.datum_veroeffentlicht ? date_format(petition.datum_veroeffentlicht) : '-' %></span>
    <span style="display:inline-block;width:350px;"><%= petition.titel %></span>
    <span style="display:inline-block;width:80px;text-align:center;"><%= petition.get_anzahl_unterstuetzer %></span>
    <span style="display:inline-block;width:80px;text-align:center;"><%= petition.get_anzahl_dagegen %></span>
    <span style="display:inline-block;width:80px;text-align:center;"><%= petition.get_anzahl_spam %></span>
    <span style="display:inline-block;width:80px;text-align:center;"><%= petition.ist_zensiert ? 'Ja' : 'Nein' %></span>
  </a>
</li>

app/views/petitionen/_form.html.erb
<%
#
# https://www.epetition-unzensiert.de - Web-Application to publish censored petitions.
# Copyright (C) 2013 Jan Kechel
#  
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
%>

<h2>Hinweis:</h2>
<ul>
  <li>Petitionen dürfen keine Namen von Personen oder Firmen enthalten.</li>
  <li>Petitionen dürfen keine Adressen, Telefonnummern, E-Mails, URLs oder Links enthalten.</li>
  <li>Petitionen dürfen keine offensichtlich illegalen Inhalte enthalten.</li>
  <li>HTML-Tags werden ausgefiltert.</li>
</ul>
<br/>
<%= form_for([@foruser, @petition]) do |f| %>
  <% if @petition.errors.any? %>
    <div id="error_explanation">
      <h2>Petition konnte nicht gespeichert werden:</h2>
      <ul>
      <% @petition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titel %><br>
    <%= f.text_field :titel, :required => true, :size => 80 %>
  </div>
  <div class="field">
    <%= f.label :inhalt %><br>
    <%= f.text_area :inhalt, :required => true, :rows => 20, :cols => 80 %>
  </div>
  <br/>

  <%= f.submit 'Speichern', :class => 'button speichern', :style => 'float:right;' %>
<% end %>

app/views/petitionen/edit.html.erb
<%
#
# https://www.epetition-unzensiert.de - Web-Application to publish censored petitions.
# Copyright (C) 2013 Jan Kechel
#  
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
%>

<h1>Petition <%= @petition.titel %> von <% @foruser.email %> bearbeiten</h1>

<%= render 'form' %>

<%= link_to 'Abbrechen', user_petition_path(@foruser, @petition), :class => 'button abbrechen' %>
<%= link_to 'Löschen', user_petition_path(@foruser, @petition), method: :delete, data: { confirm: 'Sicher?' }, :class => 'button loeschen' %>

app/views/petitionen/index.html.erb
<%
#
# https://www.epetition-unzensiert.de - Web-Application to publish censored petitions.
# Copyright (C) 2013 Jan Kechel
#  
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
%>

<h1><%= @petitionen.total_count %> Petitionen von <%= @foruser.email %></h1>
<%= paginate @petitionen %>
<ul class="trennlinien highlightonhover blocklinks">
    <li><b>
        <span style="display:inline-block;width:120px;">Veröffentlicht</span>
        <span style="display:inline-block;width:350px;">Titel</span>
        <span style="display:inline-block;width:80px;text-align:center;">Unterstützer</span>
        <span style="display:inline-block;width:80px;text-align:center;">Gegner</span>
        <span style="display:inline-block;width:80px;text-align:center;">SPAM</span>
        <span style="display:inline-block;width:80px;text-align:center;">Gesperrt?</span>
      </b>
    </li>

    <% @petitionen.each do |petition| %>
      <%= render :partial => 'petitionen/as_li', :locals => { :foruser => @foruser, :petition => petition } %>
    <% end %>
</ul>
<%= paginate @petitionen %>
<i>* Petitionen anklicken für Details und zum Bearbeiten.</i><br/>
<br>

<%= link_to 'Neue Petition erstellen', new_user_petition_path(@foruser), :class => 'button neu' %>

app/views/petitionen/new.html.erb
<%
#
# https://www.epetition-unzensiert.de - Web-Application to publish censored petitions.
# Copyright (C) 2013 Jan Kechel
#  
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
%>

<h1>Neue Petition von <%= @foruser.email %></h1>

<%= render 'form' %>

<%= link_to 'Abbrechen', user_petitionen_path(@foruser), :class => 'button abbrechen' %>

app/views/petitionen/show.html.erb
<%
#
# https://www.epetition-unzensiert.de - Web-Application to publish censored petitions.
# Copyright (C) 2013 Jan Kechel
#  
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
%>

<h1>Petition <%= @petition.titel %> von <%= @foruser.email %></h1>

  <span class="stdlabel200">Datum erstellt:</span> <%= datetime_format @petition.datum_erstellt %> <br/>
  <span class="stdlabel200">Datum zuletzt bearbeitet:</span> <%= datetime_format @petition.datum_zuletzt_bearbeitet %> <br/>
  <span class="stdlabel200">Datum veröffentlicht:</span> <%= datetime_format @petition.datum_veroeffentlicht %> <br/>
  <br/>
  <span class="stdlabel200">Titel:</span> <span class="petitionstitel"><%= @petition.titel %></span><br/>
  <br/>
  <span class="stdlabel200">Inhalt:</span> <span class="petitionstext"><%= newline2br @petition.inhalt %></span><br/>
  <br/>


  <span class="stdlabel200">Ist effektiv zensiert:</span> <%= @petition.ist_zensiert ? 'Ja' : 'Nein' %> <i>* z.B. wegen Regelverstoss, SPAM oder rechtlichen Bedenken am Inhalt.</i><br/>
  <span class="stdlabel200">Ist von Admin zensiert:</span> <%= @petition.ist_zensiert_von_admin ? 'Ja' : 'Nein' %> <br/>
<% if @petition.datum_zensiert %>
  <span class="stdlabel200">Datum zensiert:</span> <%= datetime_format @petition.datum_zensiert %> <br/>
<% end %>
<% if @petition.datum_entzensiert %>
  <span class="stdlabel200">Datum entzensiert:</span> <%= datetime_format @petition.datum_entzensiert %> <br/>
<% end %>

<br/>

  <span class="stdlabel200">Anzahl Unterstützer:</span> <%= @petition.get_anzahl_unterstuetzer %> <br/>
  <span class="stdlabel200">Anzahl Gegner:</span> <%= @petition.get_anzahl_dagegen %> <br/>
  <span class="stdlabel200">Anzahl SPAM:</span> <%= @petition.get_anzahl_spam %> <br/>
  <br/>

<%= link_to 'Meine Petitionen', user_petitionen_path(@foruser), :class => 'button zurueck' %>
<% if !@petition.datum_veroeffentlicht %>
<%= link_to 'Bearbeiten', edit_user_petition_path(@foruser, @petition), :class => 'button bearbeiten' %>
<%= link_to 'Jetzt veröffentlichen', user_petition_jetzt_veroeffentlichen_path(@foruser, @petition), :method => :patch, :class => 'button bestaetigen' %>
<% else %>
  <i>* Diese Petition wurde bereits veröffentlicht und kann nicht mehr bearbeitet werden.</i>
<% end %>
<% if current_user && current_user.is_admin %>
  <% if @petition.ist_zensiert && !@petition.datum_entzensiert %>
    <%= link_to 'Entzensieren', user_petition_entzensieren_path(@foruser, @petition), :method => :patch, :class => 'button' %>
  <% end %>
  <% if !@petition.ist_zensiert_von_admin %>
    <%= link_to 'Admin-Zensur', user_petition_admin_zensieren_path(@foruser, @petition), :method => :patch, :class => 'button' %>
  <% else %>
    <%= link_to 'keine Admin-Zensur', user_petition_nicht_admin_zensieren_path(@foruser, @petition), :method => :patch, :class => 'button' %>
  <% end %>

<% end %>