config/routes.rb
EpetitionUnzensiert::Application.routes.draw do
  devise_for :users

  get '/browser/:petition_id' => 'browser#show', :as => :browser_show, :petition_id => /\d+/
  get '/browser/index' => 'browser#index'

  resources :meinungen, :only => [] do
    collection do
      patch '/bin_unterstuetzer/:petition_id' => 'meinungen#bin_unterstuetzer', :as => :bin_unterstuetzer, :petition_id => /\d+/
      patch '/bin_dagegen/:petition_id' => 'meinungen#bin_dagegen', :as => :bin_dagegen, :petition_id => /\d+/
      patch '/habe_keine_meinung/:petition_id' => 'meinungen#habe_keine_meinung', :as => :habe_keine_meinung, :petition_id => /\d+/
      patch '/ist_spam/:petition_id' => 'meinungen#ist_spam', :as => :ist_spam, :petition_id => /\d+/
      patch '/ist_kein_spam/:petition_id' => 'meinungen#ist_kein_spam', :as => :ist_kein_spam, :petition_id => /\d+/
    end
  end

  resources :static_sites
  resources :users, :only => [:index, :show] do 
    resources :petitionen do
      patch '/jetzt_veroeffentlichen' => 'petitionen#jetzt_veroeffentlichen'
      patch '/entzensieren' => 'petitionen#entzensieren'
      patch '/admin_zensieren' => 'petitionen#admin_zensieren'
      patch '/nicht_admin_zensieren' => 'petitionen#nicht_admin_zensieren'
    end
    resources :meinungen, :only => [:index]
    patch '/ist_spammer' => 'users#ist_spammer'
    patch '/ist_kein_spammer' => 'users#ist_kein_spammer'
  end

  get '/:static_site_path' => 'static_sites#show_static_site'
  root 'static_sites#show_static_site' # index.html aus CMS ist Startseite

  get '*path' => 'application#notfound404'
end

app/models/static_site.rb
# encoding: utf-8
#
# https://www.epetition-unzensiert.de - Web-Application to publish censored petitions.
# Copyright (C) 2013 Jan Kechel
#  
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
class StaticSite < ActiveRecord::Base
  validates_presence_of :url
  validates_presence_of :html
  validates_uniqueness_of :url

  scope :correctorder, lambda { order('url')}

  scope :for_url, lambda { |url| where('url = ?', url)}

  def get_relative_url
    return "/#{url}.html"
  end
end

app/controllers/static_sites_controller.rb
# encoding: utf-8
#
# https://www.epetition-unzensiert.de - Web-Application to publish censored petitions.
# Copyright (C) 2013 Jan Kechel
#  
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
class StaticSitesController < ApplicationController
  before_filter :admin_only!, :except => [:show_static_site]

  def show_static_site
    if !params[:static_site_path] || params[:static_site_path] == ''
      @static_site = StaticSite.for_url('index').first
    else
      @static_site = StaticSite.for_url(params[:static_site_path]).first
    end

    if !@static_site
      raise NotFoundException.new
    end

    respond_to do |format|
      format.html
    end
  end


  # GET /static_sites
  # GET /static_sites.json
  def index
    @static_sites = StaticSite.correctorder

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @static_sites }
    end
  end

  # GET /static_sites/1
  # GET /static_sites/1.json
  def show
    @static_site = StaticSite.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @static_site }
    end
  end

  # GET /static_sites/new
  # GET /static_sites/new.json
  def new
    @static_site = StaticSite.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @static_site }
    end
  end

  # GET /static_sites/1/edit
  def edit
    @static_site = StaticSite.find(params[:id])
  end

  # POST /static_sites
  # POST /static_sites.json
  def create
    @static_site = StaticSite.new(params.require(:static_site).permit(:url, :title, :description, :keywords, :html))

    respond_to do |format|
      if @static_site.save
        format.html { redirect_to @static_site, :notice => 'CMS-Seite wurde erstellt.' }
        format.json { render :json => @static_site, :status => :created, :location => @static_site }
      else
        format.html { render :action => "new" }
        format.json { render :json => @static_site.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /static_sites/1
  # PUT /static_sites/1.json
  def update
    @static_site = StaticSite.find(params[:id])

    respond_to do |format|
      if @static_site.update_attributes(params.require(:static_site).permit(:url, :title, :description, :keywords, :html))
        format.html { redirect_to @static_site, :notice => 'CMS-Seite wurde gespeichert.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @static_site.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /static_sites/1
  # DELETE /static_sites/1.json
  def destroy
    @static_site = StaticSite.find(params[:id])
    @static_site.destroy

    respond_to do |format|
      format.html { redirect_to static_sites_url }
      format.json { head :no_content }
    end
  end
end

app/views/static_sites/_form.html.erb
<%
#
# https://www.epetition-unzensiert.de - Web-Application to publish censored petitions.
# Copyright (C) 2013 Jan Kechel
#  
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
%>

<% content_for :extra_js do %>
  <script type="text/javascript" src="/ckeditor/ckeditor.js"></script>
<% end %>

<%= form_for(@static_site) do |f| %>
  <% if @static_site.errors.any? %>
    <div id="error_explanation">
      <h2>CMS-Seite konnte nicht gespeichert werden:</h2>

      <ul>
      <% @static_site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <span class="stdlabel150">
    <%= f.label :url, 'URL' %></span>
    /<%= f.text_field :url %>.html

  <h2>SEO-Tags</h2>
  <span class="stdlabel150">
    <%= f.label :title %></span>
    <%= f.text_field :title %>
  <br/>
  <span class="stdlabel150">
    <%= f.label :description %></span>
    <%= f.text_field :description %>
  <br/>
  <span class="stdlabel150">
    <%= f.label :keywords %></span>
    <%= f.text_field :keywords %>
  <br/>
  <h2>HTML Source-Code</h2>
  <%= f.text_area :html, :class => 'ckeditor' %>
  <br/>
  <br/>
  <%= f.submit 'Speichern', :class => 'button speichern', :style => 'float:right;' %>
<% end %>

app/views/static_sites/edit.html.erb
<%
#
# https://www.epetition-unzensiert.de - Web-Application to publish censored petitions.
# Copyright (C) 2013 Jan Kechel
#  
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
%>

<div class="bluelinks">
<h1>CMS-Seite bearbeiten</h1>

<%= render 'form' %>

<%= link_to 'Abbrechen', static_site_path(@static_site), :class => 'button abbrechen' %>
</div>

app/views/static_sites/index.html.erb
<%
#
# https://www.epetition-unzensiert.de - Web-Application to publish censored petitions.
# Copyright (C) 2013 Jan Kechel
#  
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
%>

<div class="bluelinks-normal">
<h1>CMS-Seiten Übersicht</h1>

<table class="tdtopline highlightonhover bluelinks-normal">
  <tr>
    <th>URL</th>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @static_sites.each do |static_site| %>
  <tr>
    <td><%= link_to static_site.get_relative_url, static_site.get_relative_url %></td>
    <td><%= static_site.title %></td>
    <td><%= link_to 'Anzeigen', static_site_path(static_site) %></td>
    <td><%= link_to 'Bearbeiten', edit_static_site_path(static_site) %></td>
    <td><%= link_to 'Löschen', static_site_path(static_site), :method => :delete, :data => { :confirm => 'Sicher?' } %></td>
  </tr>
<% end %>
</table>

<br /><br />
</div>
<div class="bluelinks">
  <%= link_to 'Neue CMS-Seite erstellen', new_static_site_path, :class => 'button neu' %>
</div>

app/views/static_sites/new.html.erb
<%
#
# https://www.epetition-unzensiert.de - Web-Application to publish censored petitions.
# Copyright (C) 2013 Jan Kechel
#  
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
%>

<div class="bluelinks">
<h1>Neue CMS-Seite</h1>

<%= render 'form' %>

<%= link_to 'Abbrechen', static_sites_path, :class => 'button abbrechen' %>
</div>

app/views/static_sites/show.html.erb
<%
#
# https://www.epetition-unzensiert.de - Web-Application to publish censored petitions.
# Copyright (C) 2013 Jan Kechel
#  
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
%>

<div class="bluelinks">
<h1>CMS <%= @static_site.get_relative_url %></h1>

<p>
  <b>URL:</b>
  <%= link_to @static_site.get_relative_url, "#{@static_site.get_relative_url}", :target => "_blank" %>
</p>

<h2>SEO-Tags</h2>

<p>
  <b>Title:</b>
  <%= @static_site.title %>
</p>

<p>
  <b>Description:</b>
  <%= @static_site.description %>
</p>

<p>
  <b>Keywords:</b>
  <%= @static_site.keywords %>
</p>

<h2>HTML Source-Code</h2>
<div class="html_source">
  <pre>
  <%= @static_site.html %>
  </pre>
</div>


<%= link_to "&laquo; Übersicht".html_safe, static_sites_path, :class => 'button zurueck' %>
<%= link_to 'Bearbeiten', edit_static_site_path(@static_site), :class => 'button bearbeiten' %>
<hr/>
</div>
<h2>HTML-Vorschau</h2>
<%= @static_site.html.html_safe %>
<hr/>

app/views/static_sites/show_static_site.html.erb
<%
#
# https://www.epetition-unzensiert.de - Web-Application to publish censored petitions.
# Copyright (C) 2013 Jan Kechel
#  
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
%>

<%
  content_for(:keywords, "#{@static_site.keywords}, petition, epetition, zensiert, unzensiert, e-petition")
  content_for(:title, "#{@static_site.title}")
  content_for(:description, "#{@static_site.description}")
  @showsidebar = false
%>

<%= @static_site.html.html_safe %>