config/routes.rb
EpetitionUnzensiert::Application.routes.draw do
  devise_for :users

  get '/browser/:petition_id' => 'browser#show', :as => :browser_show, :petition_id => /\d+/
  get '/browser/index' => 'browser#index'

  resources :meinungen, :only => [] do
    collection do
      patch '/bin_unterstuetzer/:petition_id' => 'meinungen#bin_unterstuetzer', :as => :bin_unterstuetzer, :petition_id => /\d+/
      patch '/bin_dagegen/:petition_id' => 'meinungen#bin_dagegen', :as => :bin_dagegen, :petition_id => /\d+/
      patch '/habe_keine_meinung/:petition_id' => 'meinungen#habe_keine_meinung', :as => :habe_keine_meinung, :petition_id => /\d+/
      patch '/ist_spam/:petition_id' => 'meinungen#ist_spam', :as => :ist_spam, :petition_id => /\d+/
      patch '/ist_kein_spam/:petition_id' => 'meinungen#ist_kein_spam', :as => :ist_kein_spam, :petition_id => /\d+/
    end
  end

  resources :static_sites
  resources :users, :only => [:index, :show] do 
    resources :petitionen do
      patch '/jetzt_veroeffentlichen' => 'petitionen#jetzt_veroeffentlichen'
      patch '/entzensieren' => 'petitionen#entzensieren'
      patch '/admin_zensieren' => 'petitionen#admin_zensieren'
      patch '/nicht_admin_zensieren' => 'petitionen#nicht_admin_zensieren'
    end
    resources :meinungen, :only => [:index]
    patch '/ist_spammer' => 'users#ist_spammer'
    patch '/ist_kein_spammer' => 'users#ist_kein_spammer'
  end

  get '/:static_site_path' => 'static_sites#show_static_site'
  root 'static_sites#show_static_site' # index.html aus CMS ist Startseite

  get '*path' => 'application#notfound404'
end

app/controllers/browser_controller.rb
# encoding: utf-8
#
# https://www.epetition-unzensiert.de - Web-Application to publish censored petitions.
# Copyright (C) 2013 Jan Kechel
#  
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
class BrowserController < ApplicationController
  def index
    if params[:browser_page]
      session[:browser_page] = params[:browser_page]
    end

    if current_user && current_user.is_admin && params[:sortierung] && ['effektiv_zensiert', 'entzensiert', 'admin_zensiert'].include?(params[:sortierung])
      @petitionen = Petition.page(session[:browser_page])
      if params[:sortierung] == 'effektiv_zensiert'
        @petitionen = @petitionen.zensiert
      end
      if params[:sortierung] == 'entzensiert'
        @petitionen = @petitionen.entzensiert
      end
      if params[:sortierung] == 'admin_zensiert'
        @petitionen = @petitionen.von_admin_zensiert
      end

    else
      @petitionen = Petition.visible.page(session[:browser_page])
    end

    if params[:sortierung]
      @sortierung = params[:sortierung]
      session[:browser_sortierung] = @sortierung
    else
      @sortierung = session[:browser_sortierung]
    end

    if @sortierung == 'unterstuetzer'
      @petitionen = @petitionen.order('anzahl_unterstuetzer_cached asc')
    end
    if @sortierung == 'unterstuetzer_desc'
      @petitionen = @petitionen.order('anzahl_unterstuetzer_cached desc')
    end
    if @sortierung == 'dagegen'
      @petitionen = @petitionen.order('anzahl_dagegen_cached asc')
    end
    if @sortierung == 'dagegen_desc'
      @petitionen = @petitionen.order('anzahl_dagegen_cached desc')
    end
    if @sortierung == 'alphabetisch'
      @petitionen = @petitionen.order('titel asc')
    end
    if @sortierung == 'alphabetisch_desc'
      @petitionen = @petitionen.order('titel desc')
    end    
    if @sortierung == 'spam'
      @petitionen = @petitionen.order('anzahl_spam_cached asc')
    end
    if @sortierung == 'spam_desc'
      @petitionen = @petitionen.order('anzahl_spam_cached desc')
    end
    if @sortierung == 'veroeffentlichung'
      @petitionen = @petitionen.order('datum_veroeffentlicht')
    end
    if @sortierung == 'veroeffentlichung_desc'
      @petitionen = @petitionen.order('datum_veroeffentlicht desc')
    end
  end

  def show
    @petition = Petition.find(params[:petition_id])
    if @petition.ist_zensiert
      if current_user && current_user.is_admin
        redirect_to user_petition_path(@petition.user, @petition)
        return
      end
      raise NotFoundException.new
    end
    session[:last_petition_id] = @petition.id

    if current_user
      @meine_meinung = current_user.meinungen.for_petition(@petition).first
    end
  end
end

app/views/browser/index.html.erb
<%
#
# https://www.epetition-unzensiert.de - Web-Application to publish censored petitions.
# Copyright (C) 2013 Jan Kechel
#  
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
%>

<div style="clear:right; float:right; text-align:right;">
<%= form_tag browser_index_path, :method => :get do %>
<%
 auswahl = {
    'Veröffentlichungs-Datum älteste zuerst' => 'veroeffentlichung', 'Veröffentlichungs-Datum neueste zuerst' => 'veroeffentlichung_desc',
    'Anzahl Unterstützer aufsteigend' => 'unterstuetzer', 'Anzahl Unterstützer absteigend' => 'unterstuetzer_desc',
    'Anzahl Gegner aufsteigend' => 'dagegen', 'Anzahl Gegner absteigend' => 'dagegen_desc',
    'Anzahl SPAM aufsteigend' => 'spam', 'Anzahl SPAM absteigend' => 'spam_desc',
    'Alphabetisch aufsteigend' => 'alphabetisch', 'Alphabetisch absteigend' => 'alphabetisch_desc'
  }
  if current_user && current_user.is_admin 
    auswahl['effektiv zensiert'] = 'effektiv_zensiert'
    auswahl['entzensiert'] = 'entzensiert'
    auswahl['von Admin zensiert'] = 'admin_zensiert'
  end
%>
  Sortierung: <%= select_tag :sortierung, options_for_select(auswahl, @sortierung), :include_blank => true %>
  <%= submit_tag 'Los' %>
<% end %>
<br/>
<%= paginate @petitionen, :param_name => 'browser_page' %>
</div>

<h1><%= @petitionen.total_count %> Petitionen</h1>
<ul style="clear:both;" class="highlightonhover trennlinien blocklinks">
  <li>
    <b>
      <span style="display:inline-block;width:100px;">Erstellt</span>
      <span style="display:inline-block;width:450px;">Titel</span>
      <span style="display:inline-block;width:100px;text-align:center;">Unterstützer</span>
      <span style="display:inline-block;width:100px;text-align:center;">Gegner</span>
      <span style="display:inline-block;width:100px;text-align:center;">SPAM</span>
    </b>
  </li>

  <% @petitionen.each do |p| %>
    <% if p.id == session[:last_petition_id] %>
      <li class="highlight">
    <% else %>
      <li>
    <% end %>
      <a href="<%= browser_show_path(p) %>">
        <span style="display:inline-block;width:100px;"><%= date_format p.datum_veroeffentlicht %></span>
        <span style="display:inline-block;width:450px;"><%= p.titel %></span>
        <span style="display:inline-block;width:100px;text-align:center;"><%= p.get_anzahl_unterstuetzer %></span>
        <span style="display:inline-block;width:100px;text-align:center;"><%= p.get_anzahl_dagegen %></span>
        <span style="display:inline-block;width:100px;text-align:center;"><%= p.get_anzahl_spam %></span>
      </a>
    </li>
  <% end %>
</ul>
<div style="float:right;">
<%= paginate @petitionen, :param_name => 'browser_page' %>
</div>

app/views/browser/show.html.erb
<%
#
# https://www.epetition-unzensiert.de - Web-Application to publish censored petitions.
# Copyright (C) 2013 Jan Kechel
#  
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
%>

<h1>Petition: <%= @petition.titel %></h1>
<span class="petitionstext" style="width:890px;"><%= newline2br @petition.inhalt %></span>
<br/>
<br/>
<% if !@meine_meinung || (!@meine_meinung.bin_unterstuetzer && !@meine_meinung.bin_dagegen) %>
  <span class="keine_meinung">Ich habe bisher keine Meinung zu dieser Petition.</span><br/>
<% end %>

<% if @meine_meinung %>
  <% if @meine_meinung.bin_unterstuetzer %>
    <span class="unterstuetzer">Ich unterstütze diese Petition.</span><br/>
  <% end %>
  <% if @meine_meinung.bin_dagegen %>
    <span class="dagegen">Ich bin gegen diese Petition.</span><br/>
  <% end %>
  <% if @meine_meinung.ist_spam %>
    <span class="spam">Ich halte diese Petition für SPAM.</span><br/>
  <% end %>
<% end %>
<br/>
<b>Meinung ändern:</b><br/>
<br/>
<% if !@meine_meinung || !@meine_meinung.bin_unterstuetzer %>
  <%= link_to 'ich unterstütze diese Petition'.html_safe, bin_unterstuetzer_meinungen_path(@petition), :method => :patch, :class => 'button unterstuetzer', :style => 'width:280px;' %>
<% else %>
  <span style="display:inline-block;width:280px;padding-left:50px;padding-right:50px;margin-left:20px;margin-right:20px;"></span>
<% end %>
<% if !@meine_meinung || !@meine_meinung.bin_dagegen %>
  <%= link_to 'ich bin gegen diese Petition'.html_safe, bin_dagegen_meinungen_path(@petition), :method => :patch, :class => 'button dagegen', :style => 'width:280px;' %>
<% else %>
  <span style="display:inline-block;width:280px;padding-left:50px;padding-right:50px;margin-left:20px;margin-right:20px;"></span>
<% end %>
<% if @meine_meinung && (@meine_meinung.bin_dagegen || @meine_meinung.bin_unterstuetzer) %>
  <%= link_to 'ich habe keine Meinung'.html_safe, habe_keine_meinung_meinungen_path(@petition), :method => :patch, :class => 'button spam', :style => 'width:280px;' %>
<% else %>
  <span style="display:inline-block;width:280px;padding-left:50px;padding-right:50px;margin-left:20px;margin-right:20px;"></span>
<% end %>
<% if !@meine_meinung || !@meine_meinung.ist_spam %>
  <%= link_to 'diese Petition ist SPAM'.html_safe, ist_spam_meinungen_path(@petition), :method => :patch, :class => 'button spam', :style => 'width:280px;' %>
<% else %>
  <%= link_to 'diese Petition ist kein SPAM'.html_safe, ist_kein_spam_meinungen_path(@petition), :method => :patch, :class => 'button spam', :style => 'width:280px;' %>
<% end %>
<hr/>
<br/>
<%= link_to '&laquo; zurück zu alle Petitionen'.html_safe, browser_index_path %>

<% if current_user %>
  <%= link_to '&laquo; zurück zu meine Meinungen'.html_safe, user_meinungen_path(current_user) %>
  <% if current_user.is_admin %>
    <%= link_to 'Benutzer anzeigen', user_path(@petition.user) %>
    <%= link_to 'Petition anzeigen', user_petition_path(@petition.user, @petition) %>
  <% end %>
<% end %>